In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv('Olympics.csv')

In [2]:
df.head()

,Name,Sex,Age,Height,Weight,Team,Year,Season,Host_City,Host_Country,Sport,Event,GDP_Per_Capita_Constant_LCU_Value,Representing_Host,Avg_Temp,Medal
0,Andreea Aanei,F,22.0,170.0,125.0,Romania,2016,Summer,Rio de Janeiro,Brazil,Weightlifting,Weightlifting Women's Super-Heavyweight,20450.34567,0,8.8,0
1,Nstor Abad Sanjun,M,23.0,167.0,64.0,Spain,2016,Summer,Rio de Janeiro,Brazil,Gymnastics,Gymnastics Men's Individual All-Around,23788.15345,0,13.3,0
2,Nstor Abad Sanjun,M,23.0,167.0,64.0,Spain,2016,Summer,Rio de Janeiro,Brazil,Gymnastics,Gymnastics Men's Floor Exercise,23788.15345,0,13.3,0
3,Nstor Abad Sanjun,M,23.0,167.0,64.0,Spain,2016,Summer,Rio de Janeiro,Brazil,Gymnastics,Gymnastics Men's Parallel Bars,23788.15345,0,13.3,0
4,Nstor Abad Sanjun,M,23.0,167.0,64.0,Spain,2016,Summer,Rio de Janeiro,Brazil,Gymnastics,Gymnastics Men's Horizontal Bar,23788.15345,0,13.3,0

In [3]:
df.describe(include='all')

,Name,Sex,Age,Height,Weight,Team,Year,Season,Host_City,Host_Country,Sport,Event,GDP_Per_Capita_Constant_LCU_Value,Representing_Host,Avg_Temp,Medal
count,202616,202616,202616.000000,202615.000000,202615.000000,202616,202616.000000,202616,202616,202616,202616,202616,2.026160e+05,202616.000000,202616,202616.000000
unique,100178,2,NaN,NaN,NaN,203,NaN,2,29,18,51,489,NaN,NaN,148,NaN
top,Andreas Wecker,M,NaN,NaN,NaN,Germany,NaN,Summer,Atlanta,United States,Athletics,Football Men's Football,NaN,NaN,8.5,NaN
freq,32,135131,NaN,NaN,NaN,12779,NaN,161230,13675,29798,27555,3670,NaN,NaN,12779,NaN
mean,NaN,NaN,24.966480,175.298414,70.576962,NaN,1992.252626,NaN,NaN,NaN,NaN,NaN,1.016396e+06,0.057977,NaN,0.268345
std,NaN,NaN,5.472054,10.483912,14.263095,NaN,16.518691,NaN,NaN,NaN,NaN,NaN,5.839650e+06,0.233700,NaN,0.743768
min,NaN,NaN,11.000000,127.000000,25.000000,NaN,1960.000000,NaN,NaN,NaN,NaN,NaN,2.321763e+02,0.000000,NaN,0.000000
25%,NaN,NaN,21.000000,168.000000,60.000000,NaN,1980.000000,NaN,NaN,NaN,NaN,NaN,1.671118e+04,0.000000,NaN,0.000000
50%,NaN,NaN,24.000000,175.000000,70.000000,NaN,1996.000000,NaN,NaN,NaN,NaN,NaN,3.046682e+04,0.000000,NaN,0.000000
75%,NaN,NaN,28.000000,182.000000,79.000000,NaN,2006.000000,NaN,NaN,NaN,NaN,NaN,1.329136e+05,0.000000,NaN,0.000000
max,NaN,NaN,71.000000,226.000000,214.000000,NaN,2016.000000,NaN,NaN,NaN,NaN,NaN,1.313372e+08,1.000000,NaN,3.000000

In [4]:
missing_values = df.isnull().sum()

# Print the missing values
print("Missing values in each column:")
print(missing_values)

Missing values in each column:
Name                                 0
Sex                                  0
Age                                  0
Height                               1
Weight                               1
Team                                 0
Year                                 0
Season                               0
Host_City                            0
Host_Country                         0
Sport                                0
Event                                0
GDP_Per_Capita_Constant_LCU_Value    0
Representing_Host                    0
Avg_Temp                             0
Medal                                0
dtype: int64

In [5]:
numeric_columns = df.select_dtypes(include=['float64', 'int64']).columns
correlation_matrix = df[numeric_columns].corr()

# Print correlation matrix
print("\nCorrelation Matrix:")
print(correlation_matrix)

Correlation Matrix:
                                        Age    Height    Weight      Year  \
Age                                1.000000  0.148725  0.216059  0.115478
Height                             0.148725  1.000000  0.799067  0.063043
Weight                             0.216059  0.799067  1.000000  0.035977
Year                               0.115478  0.063043  0.035977  1.000000
GDP_Per_Capita_Constant_LCU_Value -0.011889 -0.038488 -0.017642  0.042180
Representing_Host                 -0.007899 -0.003152  0.000215 -0.024700
Medal                              0.029488  0.079560  0.076688  0.014306

                                   GDP_Per_Capita_Constant_LCU_Value  \
Age                                                        -0.011889
Height                                                     -0.038488
Weight                                                     -0.017642
Year                                                        0.042180
GDP_Per_Capita_Constant_LCU_Value                           1.000000
Representing_Host                                          -0.034062
Medal                                                      -0.008671

                                   Representing_Host     Medal
Age                                        -0.007899  0.029488
Height                                     -0.003152  0.079560
Weight                                      0.000215  0.076688
Year                                       -0.024700  0.014306
GDP_Per_Capita_Constant_LCU_Value          -0.034062 -0.008671
Representing_Host                           1.000000  0.069588
Medal                                       0.069588  1.000000

In [11]:
import matplotlib.pyplot as plt

# Assuming your DataFrame is named 'df'
# Select the columns for boxplots


# Create boxplots for each selected column
df["Age"].boxplot()
plt.title('Boxplots for Age')
plt.ylabel('Values')
plt.show()

df['Height'].boxplot()
plt.title('Boxplots for Height')
plt.ylabel('Values')
plt.show()
          
df['Weight'].boxplot()
plt.title('Boxplots for Weight')
plt.ylabel('Values')
plt.show()

AttributeError: 'Series' object has no attribute 'boxplot'

In [ ]:
import matplotlib.pyplot as plt

# Assuming your DataFrame is named 'df'
# Plotting the scatter plot
plt.scatter(df['Age'], df['Weight'])
plt.title('Scatter Plot: Age vs Weight')
plt.xlabel('Age')
plt.ylabel('Weight')
plt.show()

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

# Assuming your DataFrame is named 'df'
# Select the columns for boxplots
columns_to_boxplot = ['Age', 'Height', 'Weight']

# Create boxplots for each selected column
for column in columns_to_boxplot:
    plt.figure(figsize=(8, 6))
    sns.boxplot(x=df[column])
    plt.title(f'Boxplot for {column}')
    plt.xlabel(column)
    plt.show()

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

# Assuming your DataFrame is named 'df'
# Scatter plot between Age and Weight based on Gender
plt.figure(figsize=(10, 6))
sns.scatterplot(x='Age', y='Weight', hue='Sex', data=df)
plt.title('Scatter Plot: Age vs Weight (Colored by Gender)')
plt.xlabel('Age')
plt.ylabel('Weight')
plt.show()

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

# Plotting the heatmap
plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap="coolwarm", fmt=".2f", linewidths=.5)
plt.title("Correlation Matrix")
plt.show()

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

# Assuming your DataFrame is named 'df'
# Filter the DataFrame for the sport of Gymnastics
gymnastics_df = df[df['Sport'] == 'Gymnastics']

# Scatter plot between Height and Weight based on Gender for Gymnastics
plt.figure(figsize=(10, 6))
sns.scatterplot(x='Height', y='Weight', hue='Sex', data=gymnastics_df)
plt.title('Scatter Plot: Height vs Weight (Gymnastics) Colored by Gender')
plt.xlabel('Height')
plt.ylabel('Weight')
plt.show()

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

# Assuming your DataFrame is named 'df'
# Filter the DataFrame for the sport of Weightlifting
weightlifting_df = df[df['Sport'] == 'Weightlifting']

# Scatter plot between Height and Weight based on Gender for Weightlifting
plt.figure(figsize=(10, 6))
sns.scatterplot(x='Height', y='Weight', hue='Sex', data=weightlifting_df)
plt.titlele('Scatter Plot: Height vs Weight (Weightlifting) Colored by Gender')
plt.xlabel('Height')
plt.ylabel('Weight')
plt.show()

In [ ]:
import pandas as pd

# Filter the DataFrame for the sport of Swimming
swimming_df = df[df['Sport'] == 'Swimming']

# Group by 'Team' and count the number of occurrences
participation_count = swimming_df['Team'].value_counts()

# Get the top 3 participating nations
top3_nations = participation_count.head(3).index.tolist()

# Create a new DataFrame for the top 3 participating nations in Swimming
top3_swimming_df = swimming_df[swimming_df['Team'].isin(top3_nations)].copy()

# Display the top 3 participating nations
print("Top 3 Participating Nations in Swimming:")
print(top3_nations)

# Display the new DataFrame for the top 3 participating nations in Swimming
print("\nTop 3 Swimming DataFrame:")
print(top3_swimming_df)

In [ ]:
import pandas as pd

# Group by 'Sex' and calculate the average height and weight for each gender
gender_avg_stats = top3_swimming_df.groupby('Sex').agg({'Height': 'mean', 'Weight': 'mean'}).reset_index()

# Display the average height and weight based on gender
print("Average Height and Weight Based on Gender:")
print(gender_avg_stats)

In [ ]:
import pandas as pd

# Group by 'Sex' and calculate the total count of medals for each gender
gender_medal_count = top3_swimming_df.groupby('Sex')['Medal'].count()

# Display the gender-based total count of medals
print("Gender-based Total Count of Medals:")
print(gender_medal_count)

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

# Assuming your DataFrame is named 'top3_swimming_df'
# Filter the DataFrame for the top 3 participating nations
top3_nations = top3_swimming_df['Team'].value_counts().head(3).index
filtered_df = top3_swimming_df[top3_swimming_df['Team'].isin(top3_nations)]

# Set up the figure and axes
fig, axes = plt.subplots(nrows=1, ncols=2, figsize=(15, 6))

# Boxplot of height with respect to team
sns.boxplot(x='Team', y='Height', data=filtered_df, ax=axes[0])
axes[0].set_title('Boxplot of Height with Respect to Team')

# Histogram of height
sns.histplot(data=filtered_df, x='Height', bins=20, kde=True, ax=axes[1])
axes[1].set_title('Histogram of Height')

# Adjust layout for better readability
plt.tight_layout()
plt.show()

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
df=pd.read_csv('Olympics.csv')

# Set the style for better visualization
sns.set(style="whitegrid")

# Create a line plot for Years vs. Height using seaborn
plt.figure(figsize=(10, 6))
sns.lineplot(x='Year', y='Height', data=df)
plt.title('Line Plot: Years vs. Height')
plt.xlabel('Year')
plt.ylabel('Height')
plt.grid(True)
plt.show()

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
df=pd.read_csv('Olympics.csv')
# Set the style for better visualization
sns.set(style="whitegrid")

# Create a dual line chart for Years vs. Height based on Gender using seaborn
plt.figure(figsize=(12, 6))
sns.lineplot(x='Year', y='Height', hue='Sex', data=df)
plt.title('Dual Line Chart: Years vs. Height by Gender')
plt.xlabel('Year')
plt.ylabel('Height')
plt.legend(title='Gender_Column')
plt.grid(True)
plt.show()

In [ ]:

!pip install textblob
import pandas as pd
from textblob import TextBlob

# Assuming 'Text' is the column containing text data in your DataFrame
# Replace 'Text' with the actual column name in your dataset

# Example DataFrame
data = {
    'Text': ['I love this product!', 'It was okay.', 'Not satisfied with the service.', 'Amazing experience.'],
    'Year': [2020, 2020, 2021, 2021]
}

df = pd.DataFrame(data)

# Function to get sentiment polarity
def get_sentiment(text):
    analysis = TextBlob(text)
    # Assign sentiment polarity as 'positive', 'neutral', or 'negative'
    if analysis.sentiment.polarity > 0:
        return 'positive'
    elif analysis.sentiment.polarity == 0:
        return 'neutral'
    else:
        return 'negative'

# Apply sentiment analysis and create a new 'Sentiment' column
df['Sentiment'] = df['Text'].apply(get_sentiment)

# Calculate the percentage of each sentiment
sentiment_percentage = df['Sentiment'].value_counts(normalize=True) * 100

# Display the DataFrame with the new 'Sentiment' column
print("DataFrame with Sentiment column:")
print(df)

# Display the percentage of each sentiment
print("\nPercentage of Each Sentiment:")
print(sentiment_percentage)

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
from textblob import TextBlob

# Assuming 'Text' is the column containing text data in your DataFrame
# Replace 'Text' with the actual column name in your dataset

# Example DataFrame
data = {
    'Text': ['I love this product!', 'It was okay.', 'Not satisfied with the service.', 'Amazing experience.'],
    'Year': [2020, 2020, 2021, 2021]
}

df = pd.DataFrame(data)

# Function to get sentiment polarity
def get_sentiment(text):
    analysis = TextBlob(text)
    # Assign sentiment polarity as 'positive', 'neutral', or 'negative'
    if analysis.sentiment.polarity > 0:
        return 'positive'
    elif analysis.sentiment.polarity == 0:
        return 'neutral'
    else:
        return 'negative'

# Apply sentiment analysis and create a new 'Sentiment' column
df['Sentiment'] = df['Text'].apply(get_sentiment)

# Calculate the percentage of each sentiment
sentiment_percentage = df['Sentiment'].value_counts(normalize=True) * 100

# Create a pie chart for sentiment distribution
plt.figure(figsize=(8, 8))
plt.pie(sentiment_percentage, labels=sentiment_percentage.index, autopct='%1.1f%%', startangle=90, colors=['lightgreen', 'lightblue', 'lightcoral'])
plt.title('Sentiment Distribution')
plt.show()

In [ ]:
negative_percentage = sentiment_percentage.get('negative', 0)

# Calculate the percentage of athletes without negative sentiment
non_negative_percentage = 100 - negative_percentage

# Display the result
print(f"Percentage of athletes without negative sentiment: {non_negative_percentage:.2f}%")

In [ ]:
import pandas as pd
from textblob import TextBlob

# Assuming 'Text' is the column containing text data in your DataFrame
# Replace 'Text' with the actual column name in your dataset

# Example DataFrame with 'Medals' column
data = {
    'Text': ['I love this product!', 'It was okay.', 'Not satisfied with the service.', 'Amazing experience.'],
    'Medals': [2, 1, 0, 3]
}

df = pd.DataFrame(data)

# Function to get sentiment based on medal count
def get_sentiment_with_medals(medals, text):
    if medals == 1:
        return 'neutral'
    elif medals == 0:
        return 'not negative'
    elif medals > 2:
        return 'positive'
    else:
        # Default to neutral if conditions are not met
        return 'neutral'

# Apply sentiment analysis based on medal count and create a new 'Sentiment' column
df['Sentiment'] = df.apply(lambda row: get_sentiment_with_medals(row['Medals'], row['Text']), axis=1)

# Calculate the percentage of each sentiment
sentiment_percentage = df['Sentiment'].value_counts(normalize=True) * 100

# Display the DataFrame with the new 'Sentiment' column
print("DataFrame with Sentiment column:")
print(df)

# Display the percentage of each sentiment
print("\nPercentage of Each Sentiment:")
print(sentiment_percentage)

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
from textblob import TextBlob

# Assuming 'Text' is the column containing text data in your DataFrame
# Replace 'Text' with the actual column name in your dataset

# Example DataFrame with 'Medals' column
data = {
    'Text': ['I love this product!', 'It was okay.', 'Not satisfied with the service.', 'Amazing experience.'],
    'Medals': [2, 1, 0, 3]
}

df = pd.DataFrame(data)

# Function to get sentiment based on medal count
def get_sentiment_with_medals(medals, text):
    if medals == 1:
        return 'neutral'
    elif medals == 0:
        return 'not negative'
    elif medals > 2:
        return 'positive'
    else:
        # Default to neutral if conditions are not met
        return 'neutral'

# Apply sentiment analysis based on medal count and create a new 'Sentiment' column
df['Sentiment'] = df.apply(lambda row: get_sentiment_with_medals(row['Medals'], row['Text']), axis=1)

# Calculate the percentage of each sentiment
sentiment_percentage = df['Sentiment'].value_counts(normalize=True) * 100

# Define custom colors
colors = {'not negative': 'orange', 'positive': 'green', 'neutral': 'blue', 'negative': 'red'}

# Create a pie chart with custom colors
plt.figure(figsize=(8, 8))
explode = (0.1, 0, 0)  # Extract positive piece by 10%
plt.pie(sentiment_percentage, labels=sentiment_percentage.index, autopct='%1.1f%%', startangle=90, colors=[colors.get(s, s) for s in sentiment_percentage.index], explode=explode)
plt.title('Sentiment Distribution')
plt.show()

In [ ]:
import pandas as pd

# Example DataFrame with relevant columns (replace this with your actual dataset)
data = {
    'Sport': ['Judo', 'Taekwondo', 'Judo', 'Taekwondo', 'Judo', 'Taekwondo', 'Judo', 'Taekwondo'],
    'NOC': ['USA', 'KOR', 'CHN', 'USA', 'RUS', 'KOR', 'FRA', 'CHN'],
    'Medal': ['Gold', 'Silver', 'Bronze', 'Gold', 'Silver', 'Gold', 'Bronze', 'Gold'],
    'Year': [2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020]
}

olympics_df = pd.DataFrame(data)

# Function to get the top 3 participating nations for a given sport
def top_participating_nations(df, sport):
    sport_df = df[df['Sport'] == sport]
    top_nations = sport_df['NOC'].value_counts().head(3).index.tolist()
    return sport_df[sport_df['NOC'].isin(top_nations)]

# Find the top 3 participating nations for Judo and create a dataset
top_judo_df = top_participating_nations(olympics_df, 'Judo')

# Find the top 3 participating nations for Taekwondo and create a dataset
top_taekwondo_df = top_participating_nations(olympics_df, 'Taekwondo')

# Display the resulting datasets
print("Top 3 participating nations in Judo:")
print(top_judo_df)

print("\nTop 3 participating nations in Taekwondo:")
print(top_taekwondo_df)

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Example DataFrame with relevant columns (replace this with your actual dataset)
data = {
    'Sport': ['Judo', 'Judo', 'Judo', 'Judo', 'Judo', 'Taekwondo', 'Taekwondo', 'Taekwondo', 'Taekwondo', 'Taekwondo'],
    'NOC': ['JPN', 'FRA', 'RUS', 'JPN', 'KOR', 'KOR', 'CHN', 'USA', 'CHN', 'KOR'],
    'Gender': ['M', 'M', 'F', 'M', 'F', 'M', 'F', 'M', 'F', 'M'],
    'Height': [170, 180, 160, 175, 165, 175, 160, 180, 165, 170],
    'Year': [2000, 2004, 2008, 2012, 2016, 2000, 2004, 2008, 2012, 2016]
}

olympics_df = pd.DataFrame(data)

# Function to get the top 3 participating nations for a given sport
def top_participating_nations(df, sport, top_n=3):
    sport_df = df[df['Sport'] == sport]
    top_nations = sport_df['NOC'].value_counts().head(top_n).index.tolist()
    return sport_df[sport_df['NOC'].isin(top_nations)]

# Find the top 3 participating nations for Judo and Taekwondo
top_judo_df = top_participating_nations(olympics_df, 'Judo')
top_taekwondo_df = top_participating_nations(olympics_df, 'Taekwondo')

# Combine the datasets for analysis
combined_df = pd.concat([top_judo_df, top_taekwondo_df])

# Plot the distribution of height based on gender for the top 3 countries in Judo and Taekwondo
plt.figure(figsize=(10, 6))
sns.boxplot(x='NOC', y='Height', hue='Gender', data=combined_df)
plt.title('Height Distribution Based on Gender for Top 3 Countries in Judo and Taekwondo (1960-2016)')
plt.xlabel('Country')
plt.ylabel('Height (cm)')
plt.show()